Repository Mac-Win/Toucheese-BackEnd, pull requests merged in 2024-12, with the labels that each got.

#40 예약 기능 정보 저장
  src/main/java/com/toucheese/product/dto/AddOptionResponse.java
  src/main/java/com/toucheese/product/entity/Product.java
  src/main/java/com/toucheese/product/entity/ProductAddOption.java
  src/main/java/com/toucheese/product/repository/ProductAddOptionRepository.java
  src/main/java/com/toucheese/product/service/ProductService.java
  src/main/java/com/toucheese/reservation/controller/ReservationController.java
  src/main/java/com/toucheese/reservation/dto/ReservationRequest.java
  src/main/java/com/toucheese/reservation/entity/Reservation.java
  src/main/java/com/toucheese/reservation/entity/ReservationProductAddOption.java
  src/main/java/com/toucheese/reservation/entity/ReservationStatus.java
  src/main/java/com/toucheese/reservation/repository/ReservationRepository.java
  src/main/java/com/toucheese/reservation/service/ReservationService.java
  src/main/java/com/toucheese/reservation/service/ReservationValidationService.java
  src/main/java/com/toucheese/studio/service/StudioService.java
Labels: enhancement

#42 [Member] 로그인 기능 구현
  build.gradle
  src/main/java/com/toucheese/global/config/AppConfig.java
  src/main/java/com/toucheese/global/config/SecurityConfig.java
  src/main/java/com/toucheese/global/data/ApiResponse.java
  src/main/java/com/toucheese/global/exception/ToucheeseTokenInvalidException.java
  src/main/java/com/toucheese/global/exception/ToucheeseUnAuthorizedException.java
  src/main/java/com/toucheese/global/util/JwtAuthenticationFilter.java
  src/main/java/com/toucheese/global/util/JwtTokenProvider.java
  src/main/java/com/toucheese/member/controller/MemberController.java
  src/main/java/com/toucheese/member/dto/LoginRequest.java
  src/main/java/com/toucheese/member/entity/Member.java
  src/main/java/com/toucheese/member/entity/Token.java
  src/main/java/com/toucheese/member/repository/MemberRepository.java
  src/main/java/com/toucheese/member/repository/TokenRepository.java
  src/main/java/com/toucheese/member/service/MemberService.java
  src/main/java/com/toucheese/member/service/TokenService.java
  src/main/resources/application.yml
Labels: enhancement

#43 솔라피 문자 기능 구현
  build.gradle
  src/main/java/com/toucheese/global/config/SecurityConfig.java
  src/main/java/com/toucheese/global/exception/ToucheeseInternalServerErrorException.java
  src/main/java/com/toucheese/solapi/config/SolapiUtil.java
  src/main/java/com/toucheese/solapi/controller/MessageController.java
  src/main/java/com/toucheese/solapi/dto/MessageRequest.java
  src/main/java/com/toucheese/solapi/service/MessageService.java
Labels: enhancement

#46 [Member] 토큰 검증 및 갱신 로직 수정
  src/main/java/com/toucheese/global/data/JwtValidateStatus.java
  src/main/java/com/toucheese/global/util/JwtAuthenticationFilter.java
  src/main/java/com/toucheese/global/util/JwtTokenProvider.java
  src/main/java/com/toucheese/member/repository/TokenRepository.java
  src/main/java/com/toucheese/member/service/TokenService.java
Labels: refactoring

#49 [Member] 로그인 응답 형식 변경
  src/main/java/com/toucheese/global/config/SecurityConfig.java
  src/main/java/com/toucheese/global/data/ApiResponse.java
  src/main/java/com/toucheese/member/controller/MemberController.java
  src/main/java/com/toucheese/member/dto/LoginMemberResponse.java
  src/main/java/com/toucheese/member/dto/LoginResponse.java
  src/main/java/com/toucheese/member/service/MemberService.java
Labels: refactoring

#51 [Image] 이미지 로딩 속도 개선
  .gitignore
  build.gradle
  src/main/java/com/toucheese/conceptstudio/dto/StudioResponse.java
  src/main/java/com/toucheese/conceptstudio/service/ConceptStudioService.java
  src/main/java/com/toucheese/global/config/ImageConfig.java
  src/main/java/com/toucheese/global/config/S3Config.java
  src/main/java/com/toucheese/image/controller/ImageController.java
  src/main/java/com/toucheese/image/entity/StudioImage.java
  src/main/java/com/toucheese/image/repository/StudioImageRepository.java
  src/main/java/com/toucheese/image/service/ImageService.java
  src/main/java/com/toucheese/image/util/S3ImageUtil.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: performance

#52 [Image] 이미지 업로드 기능 구현 및 리팩토링
  src/main/java/com/toucheese/conceptstudio/service/ConceptStudioService.java
  src/main/java/com/toucheese/global/config/ImageConfig.java
  src/main/java/com/toucheese/image/controller/ImageController.java
  src/main/java/com/toucheese/image/entity/StudioImage.java
  src/main/java/com/toucheese/image/repository/StudioImageRepository.java
  src/main/java/com/toucheese/image/service/ImageService.java
  src/main/java/com/toucheese/image/util/FilenameUtil.java
  src/main/java/com/toucheese/image/util/S3ImageUtil.java
Labels: enhancement, refactoring

#53 예약 및 장바구니 기능 구현
  build.gradle
  src/main/java/com/toucheese/cart/controller/CartController.java
  src/main/java/com/toucheese/cart/dto/CartIdsRequest.java
  src/main/java/com/toucheese/cart/dto/CartRequest.java
  src/main/java/com/toucheese/cart/dto/CartResponse.java
  src/main/java/com/toucheese/cart/dto/CartUpdateRequest.java
  src/main/java/com/toucheese/cart/dto/CheckoutCartItemsResponse.java
  src/main/java/com/toucheese/cart/dto/CombinedResponse.java
  src/main/java/com/toucheese/cart/dto/SelectAddOptionResponse.java
  src/main/java/com/toucheese/cart/entity/Cart.java
  src/main/java/com/toucheese/cart/repository/CartRepository.java
  src/main/java/com/toucheese/cart/service/CartReadService.java
  src/main/java/com/toucheese/cart/service/CartService.java
  src/main/java/com/toucheese/global/config/AsyncConfig.java
  src/main/java/com/toucheese/global/config/SwaggerConfig.java
  src/main/java/com/toucheese/global/util/CsvUtils.java
  src/main/java/com/toucheese/global/util/PrincipalUtils.java
  src/main/java/com/toucheese/member/controller/MemberController.java
  src/main/java/com/toucheese/member/dto/MemberContactInfoResponse.java
  src/main/java/com/toucheese/member/entity/Member.java
  src/main/java/com/toucheese/member/service/MemberService.java
  src/main/java/com/toucheese/product/repository/AddOptionRepository.java
  src/main/java/com/toucheese/product/service/ProductService.java
  src/main/java/com/toucheese/reservation/controller/ReservationController.java
  src/main/java/com/toucheese/reservation/dto/ReservationRequest.java
  src/main/java/com/toucheese/reservation/entity/Reservation.java
  src/main/java/com/toucheese/reservation/entity/ReservationStatus.java
  src/main/java/com/toucheese/reservation/event/ReservationMessageEvent.java
  src/main/java/com/toucheese/reservation/service/ReservationService.java
  src/main/java/com/toucheese/reservation/service/ReservationValidationService.java
  src/main/java/com/toucheese/solapi/controller/MessageController.java
  src/main/java/com/toucheese/solapi/service/MessageService.java
  src/main/resources/application.yml
Labels: enhancement, refactoring

#55 관리자 예약 전체 조회 상태 변경 기능 구현
  src/main/java/com/toucheese/admin/controller/AdminReservationController.java
  src/main/java/com/toucheese/admin/dto/AdminReservationListResponse.java
  src/main/java/com/toucheese/admin/dto/UpdateReservationStatusRequest.java
  src/main/java/com/toucheese/admin/service/AdminReservationService.java
  src/main/java/com/toucheese/cart/dto/SelectAddOptionResponse.java
  src/main/java/com/toucheese/global/config/SecurityConfig.java
  src/main/java/com/toucheese/global/util/JwtAuthenticationFilter.java
  src/main/java/com/toucheese/global/util/JwtTokenProvider.java
  src/main/java/com/toucheese/member/entity/Member.java
  src/main/java/com/toucheese/member/entity/Role.java
  src/main/java/com/toucheese/member/service/TokenService.java
  src/main/java/com/toucheese/reservation/dto/ReservationRequest.java
  src/main/java/com/toucheese/reservation/dto/ReservationResponse.java
  src/main/java/com/toucheese/reservation/entity/Reservation.java
  src/main/java/com/toucheese/reservation/repository/ReservationRepository.java
  src/main/java/com/toucheese/reservation/service/ReservationService.java
  src/main/java/com/toucheese/solapi/controller/MessageController.java
Labels: enhancement, refactoring

#58 [공통] 3차 스프린트 코드 리팩토링
  src/main/java/com/toucheese/admin/controller/AdminReservationController.java
  src/main/java/com/toucheese/cart/controller/CartController.java
  src/main/java/com/toucheese/cart/service/CartService.java
  src/main/java/com/toucheese/concept/controller/ConceptController.java
  src/main/java/com/toucheese/conceptstudio/controller/ConceptStudioController.java
  src/main/java/com/toucheese/global/advice/ControllerAdvice.java
  src/main/java/com/toucheese/global/advice/CustomAuthenticationEntryPoint.java
  src/main/java/com/toucheese/global/config/SecurityConfig.java
  src/main/java/com/toucheese/global/data/ApiResponse.java
  src/main/java/com/toucheese/global/exception/ToucheeseTokenInvalidException.java
  src/main/java/com/toucheese/global/exception/ToucheeseUnAuthorizedException.java
  src/main/java/com/toucheese/global/util/JwtAuthenticationFilter.java
  src/main/java/com/toucheese/global/util/JwtTokenProvider.java
  src/main/java/com/toucheese/global/util/TokenUtils.java
  src/main/java/com/toucheese/member/controller/MemberController.java
  src/main/java/com/toucheese/member/controller/TokenController.java
  src/main/java/com/toucheese/member/dto/LoginRequest.java
  src/main/java/com/toucheese/member/dto/LoginResponse.java
  src/main/java/com/toucheese/member/dto/MemberTokenResponse.java
  src/main/java/com/toucheese/member/dto/ReissueRequest.java
  src/main/java/com/toucheese/member/dto/TokenDTO.java
  src/main/java/com/toucheese/member/entity/Token.java
  src/main/java/com/toucheese/member/repository/TokenRepository.java
  src/main/java/com/toucheese/member/service/MemberService.java
  src/main/java/com/toucheese/member/service/TokenService.java
  src/main/java/com/toucheese/product/controller/ProductController.java
  src/main/java/com/toucheese/reservation/controller/ReservationController.java
  src/main/java/com/toucheese/review/controller/ReviewController.java
  src/main/java/com/toucheese/studio/controller/StudioController.java
Labels: refactoring

#61 [Image] 이미지 응답 형식 변경
  src/main/java/com/toucheese/conceptstudio/dto/StudioResponse.java
  src/main/java/com/toucheese/image/controller/ImageController.java
  src/main/java/com/toucheese/image/entity/FacilityImage.java
  src/main/java/com/toucheese/image/entity/ImageType.java
  src/main/java/com/toucheese/image/entity/ReviewImage.java
  src/main/java/com/toucheese/image/repository/FacilityImageRepository.java
  src/main/java/com/toucheese/image/repository/ReviewImageRepository.java
  src/main/java/com/toucheese/image/service/ImageService.java
  src/main/java/com/toucheese/product/dto/ProductResponse.java
  src/main/java/com/toucheese/review/dto/ReviewDetailResponse.java
  src/main/java/com/toucheese/review/dto/ReviewResponse.java
  src/main/java/com/toucheese/review/service/ReviewService.java
  src/main/java/com/toucheese/studio/dto/StudioDetailResponse.java
  src/main/java/com/toucheese/studio/service/StudioService.java
Labels: enhancement, refactoring

#60 사용자 예약 조회 및 수정 기능 구현
  src/main/java/com/toucheese/ToucheeseApplication.java
  src/main/java/com/toucheese/admin/controller/AdminReservationController.java
  src/main/java/com/toucheese/admin/dto/AdminReservationListResponse.java
  src/main/java/com/toucheese/admin/service/AdminReservationService.java
  src/main/java/com/toucheese/cart/controller/CartController.java
  src/main/java/com/toucheese/cart/dto/CartRequest.java
  src/main/java/com/toucheese/cart/dto/CartResponse.java
  src/main/java/com/toucheese/cart/dto/CheckoutCartItemsResponse.java
  src/main/java/com/toucheese/cart/service/CartService.java
  src/main/java/com/toucheese/conceptstudio/service/ConceptStudioService.java
  src/main/java/com/toucheese/global/util/PageUtils.java
  src/main/java/com/toucheese/product/dto/ProductDetailResponse.java
  src/main/java/com/toucheese/product/service/ProductService.java
  src/main/java/com/toucheese/reservation/controller/ReservationController.java
  src/main/java/com/toucheese/reservation/dto/ReservationRequest.java
  src/main/java/com/toucheese/reservation/dto/ReservationResponse.java
  src/main/java/com/toucheese/reservation/dto/ReservationUpdateRequest.java
  src/main/java/com/toucheese/reservation/entity/Reservation.java
  src/main/java/com/toucheese/reservation/entity/ReservationStatus.java
  src/main/java/com/toucheese/reservation/repository/ReservationRepository.java
  src/main/java/com/toucheese/reservation/service/ReservationReadService.java
  src/main/java/com/toucheese/reservation/service/ReservationSchedulerService.java
  src/main/java/com/toucheese/reservation/service/ReservationService.java
  src/main/java/com/toucheese/studio/entity/OperatingHour.java
  src/main/resources/application.yml
Labels: enhancement

#66 [Image] 이미지 업로드 기능 리팩토링
  src/main/java/com/toucheese/admin/service/AdminAnswerService.java
  src/main/java/com/toucheese/image/controller/ImageController.java
  src/main/java/com/toucheese/image/entity/FacilityImage.java
  src/main/java/com/toucheese/image/entity/ImageInfo.java
  src/main/java/com/toucheese/image/entity/QuestionImage.java
  src/main/java/com/toucheese/image/entity/ReviewImage.java
  src/main/java/com/toucheese/image/entity/StudioImage.java
  src/main/java/com/toucheese/image/repository/FacilityImageRepository.java
  src/main/java/com/toucheese/image/repository/ImageInfoRepository.java
  src/main/java/com/toucheese/image/repository/QuestionImageRepository.java
  src/main/java/com/toucheese/image/repository/ReviewImageRepository.java
  src/main/java/com/toucheese/image/repository/StudioImageRepository.java
  src/main/java/com/toucheese/image/service/ImageFacade.java
  src/main/java/com/toucheese/image/service/ImageInfoService.java
  src/main/java/com/toucheese/image/service/ImageService.java
  src/main/java/com/toucheese/image/util/FilenameUtil.java
  src/main/java/com/toucheese/image/util/MetadataUtil.java
  src/main/java/com/toucheese/image/util/S3ImageUtil.java
  src/main/java/com/toucheese/question/controller/QuestionController.java
  src/main/java/com/toucheese/question/dto/QuestionDetailResponse.java
  src/main/java/com/toucheese/question/dto/QuestionResponse.java
  src/main/java/com/toucheese/question/entity/Question.java
  src/main/java/com/toucheese/question/service/QuestionService.java
  src/main/resources/application.yml
Labels: enhancement, refactoring

#68 문의하기 변경
  src/main/java/com/toucheese/admin/controller/AdminAnswerController.java
  src/main/java/com/toucheese/admin/service/AdminAnswerService.java
Labels: refactoring

#70 소셜 로그인 기능 구현 [ 카카오 ]
  build.gradle
  src/main/java/com/toucheese/admin/controller/AdminAnswerController.java
  src/main/java/com/toucheese/admin/service/AdminAnswerService.java
  src/main/java/com/toucheese/cart/controller/CartController.java
  src/main/java/com/toucheese/global/config/SecurityConfig.java
  src/main/java/com/toucheese/global/config/WebClientConfig.java
  src/main/java/com/toucheese/image/controller/ImageController.java
  src/main/java/com/toucheese/member/controller/AuthController.java
  src/main/java/com/toucheese/member/controller/MemberController.java
  src/main/java/com/toucheese/member/dto/AuthProvider.java
  src/main/java/com/toucheese/member/dto/KakaoCodeRequest.java
  src/main/java/com/toucheese/member/dto/KakaoMember.java
  src/main/java/com/toucheese/member/dto/MemberFirstLoginUpdateRequest.java
  src/main/java/com/toucheese/member/dto/SocalLoginCombinedResponse.java
  src/main/java/com/toucheese/member/dto/SocialLoginRequest.java
  src/main/java/com/toucheese/member/dto/SocialLoginResponse.java
  src/main/java/com/toucheese/member/entity/Member.java
  src/main/java/com/toucheese/member/repository/TokenRepository.java
  src/main/java/com/toucheese/member/service/KakaoAuthService.java
  src/main/java/com/toucheese/member/service/MemberService.java
  src/main/java/com/toucheese/member/service/TokenService.java
  src/main/java/com/toucheese/question/controller/QuestionController.java
  src/main/java/com/toucheese/question/entity/Answer.java
  src/main/java/com/toucheese/question/entity/Question.java
  src/main/java/com/toucheese/question/repository/AnswerRepository.java
  src/main/java/com/toucheese/question/repository/QuestionRepository.java
  src/main/java/com/toucheese/studio/repository/OperatingHourRepository.java
  src/main/java/com/toucheese/studio/service/StudioService.java
  src/main/java/com/toucheese/studio/util/SlotUtils.java
Labels: enhancement

#71 [Image] 문의, 리뷰 이미지 업로드 기능 통합
  src/main/java/com/toucheese/image/service/ImageFacade.java
  src/main/java/com/toucheese/member/entity/Member.java
  src/main/java/com/toucheese/question/controller/QuestionController.java
  src/main/java/com/toucheese/question/dto/QuestionRequest.java
  src/main/java/com/toucheese/question/service/QuestionService.java
  src/main/java/com/toucheese/review/controller/ReviewController.java
  src/main/java/com/toucheese/review/dto/ReviewRequest.java
  src/main/java/com/toucheese/review/entity/Review.java
  src/main/java/com/toucheese/review/service/ReviewCommandService.java
  src/main/java/com/toucheese/review/service/ReviewQueryService.java
  src/main/java/com/toucheese/studio/dto/StudioDetailResponse.java
  src/main/java/com/toucheese/studio/entity/Studio.java
Labels: enhancement, refactoring

#72 [공통] 이미지 업로드 시 null 처리 추가, 토큰 재발급 로직 수정
  src/main/java/com/toucheese/global/util/JwtTokenProvider.java
  src/main/java/com/toucheese/member/controller/TokenController.java
  src/main/java/com/toucheese/member/service/TokenService.java
  src/main/java/com/toucheese/question/service/QuestionService.java
  src/main/java/com/toucheese/review/service/ReviewCommandService.java
  src/main/java/com/toucheese/studio/util/SlotUtils.java
Labels: bug, fix

#75 [Member] 내 정보 조회 기능 구현
  src/main/java/com/toucheese/member/controller/MemberController.java
  src/main/java/com/toucheese/member/dto/MemberResponse.java
Labels: enhancement
