Repository Mac-Win/Toucheese-BackEnd, pull requests merged in 2024-11, with the labels that each got.

#19 WebConfig 전체 접근 허용
  src/main/java/com/toucheese/global/config/WebConfig.java
Labels: bug, enhancement

#20 [공통] 1차 스프린트 코드 리팩토링
  src/main/generated/com/toucheese/concept/entity/QConcept.java
  src/main/java/com/toucheese/concept/controller/ConceptController.java
  src/main/java/com/toucheese/concept/service/ConceptService.java
  src/main/java/com/toucheese/conceptstudio/controller/ConceptStudioController.java
  src/main/java/com/toucheese/conceptstudio/dto/ConceptStudioResponse.java
  src/main/java/com/toucheese/conceptstudio/dto/StudioResponse.java
  src/main/java/com/toucheese/conceptstudio/service/ConceptStudioService.java
  src/main/java/com/toucheese/studio/controller/StudioController.java
  src/main/java/com/toucheese/studio/dto/FilteringStudioRequest.java
  src/main/java/com/toucheese/studio/repository/StudioRepositoryImpl.java
  src/main/java/com/toucheese/studio/service/StudioService.java
Labels: refactoring

#24 스프린트2 - 연관관계 설정
  src/main/generated/com/toucheese/image/entity/QFacilityImage.java
  src/main/generated/com/toucheese/image/entity/QReviewImage.java
  src/main/generated/com/toucheese/image/entity/QStudioImage.java
  src/main/generated/com/toucheese/product/entity/QAddOption.java
  src/main/generated/com/toucheese/product/entity/QProduct.java
  src/main/generated/com/toucheese/product/entity/QProductAddOption.java
  src/main/generated/com/toucheese/review/entity/QReview.java
  src/main/generated/com/toucheese/studio/entity/QStudio.java
  src/main/java/com/toucheese/conceptstudio/dto/StudioResponse.java
  src/main/java/com/toucheese/image/entity/FacilityImage.java
  src/main/java/com/toucheese/image/entity/ReviewImage.java
  src/main/java/com/toucheese/image/entity/StudioImage.java
  src/main/java/com/toucheese/product/entity/AddOption.java
  src/main/java/com/toucheese/product/entity/Product.java
  src/main/java/com/toucheese/product/entity/ProductAddOption.java
  src/main/java/com/toucheese/review/entity/Review.java
  src/main/java/com/toucheese/studio/entity/Studio.java
Labels: enhancement

#26 [Studio, Product] 스튜디오, 상품 상세 조회 기능 구현
  src/main/java/com/toucheese/global/advice/ControllerAdvice.java
  src/main/java/com/toucheese/global/exception/ToucheeseBadRequestException.java
  src/main/java/com/toucheese/global/exception/ToucheeseException.java
  src/main/java/com/toucheese/product/controller/ProductController.java
  src/main/java/com/toucheese/product/dto/AddOptionResponse.java
  src/main/java/com/toucheese/product/dto/ProductDetailResponse.java
  src/main/java/com/toucheese/product/dto/ProductResponse.java
  src/main/java/com/toucheese/product/entity/AddOption.java
  src/main/java/com/toucheese/product/entity/Product.java
  src/main/java/com/toucheese/product/entity/ProductAddOption.java
  src/main/java/com/toucheese/product/repository/ProductRepository.java
  src/main/java/com/toucheese/product/service/ProductService.java
  src/main/java/com/toucheese/studio/controller/StudioController.java
  src/main/java/com/toucheese/studio/dto/StudioDetailResponse.java
  src/main/java/com/toucheese/studio/entity/Studio.java
  src/main/java/com/toucheese/studio/service/StudioService.java
Labels: enhancement

#31 swagger api 적용
  build.gradle
  src/main/generated/com/toucheese/product/entity/QAddOption.java
  src/main/generated/com/toucheese/product/entity/QProduct.java
  src/main/generated/com/toucheese/product/entity/QProductAddOption.java
  src/main/generated/com/toucheese/studio/entity/QStudio.java
  src/main/java/com/toucheese/concept/controller/ConceptController.java
  src/main/java/com/toucheese/conceptstudio/controller/ConceptStudioController.java
  src/main/java/com/toucheese/product/controller/ProductController.java
  src/main/java/com/toucheese/review/controller/ReviewController.java
  src/main/java/com/toucheese/studio/controller/StudioController.java
  src/main/resources/application.yml
Labels: enhancement

#33 feat : columnDefinition = "TEXT" 추가
  src/main/java/com/toucheese/product/entity/Product.java
  src/main/java/com/toucheese/review/entity/Review.java
Labels: enhancement

#35 [공통] 2차 스프린트 코드 리팩토링
  .gitignore
  .idea/.gitignore
  .idea/misc.xml
  .idea/modules.xml
  .idea/toucheese.iml
  .idea/vcs.xml
  src/main/generated/com/toucheese/concept/entity/QConcept.java
  src/main/generated/com/toucheese/conceptstudio/entity/QConceptStudio.java
  src/main/generated/com/toucheese/image/entity/QFacilityImage.java
  src/main/generated/com/toucheese/image/entity/QReviewImage.java
  src/main/generated/com/toucheese/image/entity/QStudioImage.java
  src/main/generated/com/toucheese/product/entity/QAddOption.java
  src/main/generated/com/toucheese/product/entity/QProduct.java
  src/main/generated/com/toucheese/product/entity/QProductAddOption.java
  src/main/generated/com/toucheese/review/entity/QReview.java
  src/main/generated/com/toucheese/studio/entity/QStudio.java
  src/main/java/com/toucheese/concept/controller/ConceptController.java
  src/main/java/com/toucheese/concept/dto/ConceptResponse.java
  src/main/java/com/toucheese/concept/service/ConceptService.java
  src/main/java/com/toucheese/conceptstudio/dto/StudioResponse.java
  src/main/java/com/toucheese/conceptstudio/service/ConceptStudioService.java
  src/main/java/com/toucheese/global/exception/ToucheeseBadRequestException.java
  src/main/java/com/toucheese/review/dto/ReviewDetailResponse.java
  src/main/java/com/toucheese/review/service/ReviewService.java
  src/main/java/com/toucheese/studio/service/StudioService.java
Labels: refactoring
